### PR TITLE
FEAT/Example - Download all trade data for an account timeline in JSON format plus all PDF files

### PR DESCRIPTION
**Pull request by blessio**
Hi, 

Happy new year to everyone :-)

There are 2 commits - these are:
- Improved Exception Interface (potentially a breaking change, although it should not be)  
- Processing of a server-side state "E"(not sure what it means - my understanding is: _"Server-side critical error – please re-initiate the connection"_) 

The second commit is a script that uses these changes to download in JSON format the complete timeline and the details for it plus ALL the PDF documents in a dedicated folder.  

Best Regards,
Blessio

### CODE REVIEW

**Comment by Zarathustra2** [comment]
Wow, nice work. That looks awesome, pretty big changes!! 

Let me know when u are comfortable and I will take a second look over it and then merge it!

**Comment by blessio** [comment]
Please have a second look and use all the time you need - the change in the API is somewhat risky... probably we can rename it public apiv2.0

**Comment by Zarathustra2** [comment]
I am fine with the changes, like the new custom exceptions. As for server state `E`, I am also unsure but ur explanation makes sense! Can be merged  IMO

**Comment by Zarathustra2** [comment]
@blessio I can merge now if you'd like to

**Comment by blessio** [comment]
@Zarathustra2 
   I am fine with the merge- thanks :)

**Pull request merged**
